### PR TITLE
[MI-3741]: Test exported types from mm-ui-lib and Fix modal type issue

### LINKED ISSUE #100: Error in importing of subComponents of Modal
## Summary
There's an issue in the importing of subComponents types in the file `src/components/Modal/Modal.d.ts`. The imports work fine in the mm-ui-library but after building, when we use the component inside a plugin, the imports of `ModalFooterProps` and `ModalHeaderProps` are not resolving, due to which we are not able to use the props inside them like `title`, `subtitle` etc.

#### Version / Branch
The branch this is reproduced on is `downgrade-bootstrap-epic`.

#### Links
https://github.com/Brightscout/mm-ui-library/blob/5dd6cdee05f817f2cd8c721c90cd5765b6be5539/src/components/Modal/Modal.d.ts#L3

#### Errors
```
Type '{ children: Element; show: boolean; onCloseHandler: () => void; onSubmitHandler: () => void; title: string; subtitle: string; className: string; primaryActionText: string; secondaryActionText: string; isPrimaryButtonDisabled: boolean; }' is not assignable to type 'IntrinsicAttributes & ModalProps'.
  Property 'title' does not exist on type 'IntrinsicAttributes & ModalProps'.
```

### PR DESCRIPTION
**Pull request by thisisankur0**
Ticket ID
[MI-3741](https://brightscout.atlassian.net/browse/MI-3741)

Description
- Test exported types
- Update build script to include nested children types: Removed redundant glob pattern

fixes #100

### CODE REVIEW

File: src/components/Spinner/index.ts [hunk 1]
```diff
@@ -1,2 +1,2 @@
 export {Spinner} from './Spinner.component';
-export type {SpinnerProps} from './Spinner';
+export type {SpinnerProps, SpinnerContainerProps} from './Spinner';
```
Comment (ayusht2810) [inline src/components/Spinner/index.ts]: why this change?

File: src/components/index.ts [hunk 2]
```diff
@@ -20,30 +24,26 @@ export {Tabs} from './Tabs';
...
+export type {ListPropType, ListItemType} from './List';
 export type {MenuItemProps} from './MenuItem';
-export type {ModalProps} from './Modal';
 export type {NoDataProps} from './NoData';
 export type {OverlayProps} from './Overlay';
 export type {RadioProps} from './Radio';
 export type {SelectProps} from './Select';
 export type {CircularSkeleton, RectangularSkeleton, SkeletonProps} from './Skeleton';
-export type {SpinnerProps} from './Spinner';
+export type {SpinnerProps, SpinnerContainerProps} from './Spinner';
```
Comment (ayusht2810) [inline src/components/index.ts]: same

**Review by ayusht2810 — APPROVED** [review]

**Review by ayusht2810 — APPROVED** [review]

**Review by manojmalik20 — APPROVED** [review]
